
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javawebsite?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver

server:
  port: 8080

#mybatis:
#mapper-locations: classpath:Mapper/*Mapper.xml